export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = "SET_INGREDIENTS";
export const FETCH_INGREDIENTS_FAILED = "FETCH_INGREDIENTS_FAILED";

export const PURCHASE_BURGER_SUCCEED = "PURCHASE_BURGER_SUCCEED";
export const PURCHASE_BURGER_FAILED = "PURCHASE_BURGER_FAILED";
export const PUCHASE_BURDER_STARTED = "PUCHASE_BURDER_STARTED";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_ORDERS_STARTED = "FETCH_ORDERS_STARTED";
export const FETCH_ORDERS_SUCCEED = "FETCH_ORDERS_SUCCEED";
export const FETCH_ORDERS_FAILED = "FETCH_ORDERS_FAILED";
